#!/bin/bash

# Legal AI System - Environment Setup Script
# This script sets up the complete environment for the Legal AI System

set -e

echo "🚀 Setting up Legal AI System Environment..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Node.js is installed
check_nodejs() {
    print_status "Checking Node.js installation..."
    if command -v node &> /dev/null; then
        NODE_VERSION=$(node --version)
        print_success "Node.js is installed: $NODE_VERSION"
    else
        print_error "Node.js is not installed. Please install Node.js first."
        exit 1
    fi
}

# Check if npm is installed
check_npm() {
    print_status "Checking npm installation..."
    if command -v npm &> /dev/null; then
        NPM_VERSION=$(npm --version)
        print_success "npm is installed: $NPM_VERSION"
    else
        print_error "npm is not installed. Please install npm first."
        exit 1
    fi
}

# Install Node.js dependencies
install_dependencies() {
    print_status "Installing Node.js dependencies..."
    
    # Create package.json if it doesn't exist
    if [ ! -f "package.json" ]; then
        cat > package.json << EOF
{
  "name": "legal-ai-system",
  "version": "1.0.0",
  "description": "Legal AI System for N8N workflow automation",
  "main": "index.js",
  "scripts": {
    "setup-sheets": "node setup-google-sheets.js",
    "setup-drive": "node setup-google-drive.js",
    "setup-all": "npm run setup-sheets && npm run setup-drive",
    "test": "node test-workflow.js"
  },
  "dependencies": {
    "google-spreadsheet": "^4.1.2",
    "googleapis": "^128.0.0",
    "google-auth-library": "^9.0.0",
    "dotenv": "^16.3.1"
  },
  "devDependencies": {
    "nodemon": "^3.0.2"
  },
  "keywords": ["legal", "ai", "automation", "n8n", "google-sheets", "google-drive"],
  "author": "Legal AI System",
  "license": "MIT"
}
EOF
        print_success "Created package.json"
    fi
    
    npm install
    print_success "Dependencies installed successfully"
}

# Create environment configuration file
create_env_file() {
    print_status "Creating environment configuration file..."
    
    cat > .env.example << EOF
# Legal AI System Configuration
# Copy this file to .env and fill in your actual values

# Google Service Account Credentials
GOOGLE_PROJECT_ID=your-project-id
GOOGLE_PRIVATE_KEY_ID=your-private-key-id
GOOGLE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
GOOGLE_CLIENT_EMAIL=your-service-account@your-project.iam.gserviceaccount.com
GOOGLE_CLIENT_ID=your-client-id

# OpenAI Configuration
OPENAI_API_KEY=your-openai-api-key

# Gmail Configuration
GMAIL_USER_EMAIL=your-email@gmail.com
GMAIL_CLIENT_ID=your-gmail-client-id
GMAIL_CLIENT_SECRET=your-gmail-client-secret
GMAIL_REFRESH_TOKEN=your-gmail-refresh-token

# Legal Team Configuration
LEGAL_TEAM_EMAIL=legal-team@yourfirm.com

# Google Sheets IDs (will be generated by setup scripts)
LEGAL_SUMMARIES_SHEET_ID=
CONTRACT_ANALYSIS_SHEET_ID=

# Google Drive Folder IDs (will be generated by setup scripts)
COMPLAINTS_CONTRACTS_FOLDER_ID=
CONTRACT_ANALYSIS_FOLDER_ID=

# N8N Configuration
N8N_HOST=http://localhost:5678
N8N_API_KEY=your-n8n-api-key
EOF

    if [ ! -f ".env" ]; then
        cp .env.example .env
        print_success "Created .env file from template"
        print_warning "Please edit .env file with your actual configuration values"
    else
        print_warning ".env file already exists, skipping creation"
    fi
}

# Create N8N configuration update script
create_n8n_config_script() {
    print_status "Creating N8N configuration update script..."
    
    cat > update-n8n-config.js << 'EOF'
/**
 * N8N Configuration Update Script
 * Updates the N8N workflow JSON with the correct IDs from environment variables
 */

const fs = require('fs');
const path = require('path');
require('dotenv').config();

function updateN8NWorkflow() {
    try {
        console.log('🔄 Updating N8N workflow configuration...');
        
        // Read the workflow JSON file
        const workflowPath = path.join(__dirname, 'legal-ai-system-n8n-workflow.json');
        const workflowData = JSON.parse(fs.readFileSync(workflowPath, 'utf8'));
        
        // Update sheet IDs
        const sheetIdMappings = {
            'legal-summaries-sheet-id': process.env.LEGAL_SUMMARIES_SHEET_ID,
            'contract-analysis-sheet-id': process.env.CONTRACT_ANALYSIS_SHEET_ID
        };
        
        // Update folder IDs
        const folderIdMappings = {
            'complaints-contracts-folder-id': process.env.COMPLAINTS_CONTRACTS_FOLDER_ID,
            'contract-analysis-folder-id': process.env.CONTRACT_ANALYSIS_FOLDER_ID
        };
        
        // Update email addresses
        const emailMappings = {
            'legal-team@yourfirm.com': process.env.LEGAL_TEAM_EMAIL
        };
        
        // Function to update node parameters recursively
        function updateNodeParameters(node) {
            if (node.parameters) {
                // Update sheet IDs
                Object.keys(sheetIdMappings).forEach(placeholder => {
                    if (node.parameters.documentId && node.parameters.documentId.value === placeholder) {
                        node.parameters.documentId.value = sheetIdMappings[placeholder];
                        console.log(`✅ Updated ${placeholder} to ${sheetIdMappings[placeholder]}`);
                    }
                });
                
                // Update folder IDs
                Object.keys(folderIdMappings).forEach(placeholder => {
                    if (node.parameters.folderId && node.parameters.folderId.value === placeholder) {
                        node.parameters.folderId.value = folderIdMappings[placeholder];
                        console.log(`✅ Updated ${placeholder} to ${folderIdMappings[placeholder]}`);
                    }
                });
                
                // Update email addresses
                Object.keys(emailMappings).forEach(placeholder => {
                    if (node.parameters.toEmail === placeholder) {
                        node.parameters.toEmail = emailMappings[placeholder];
                        console.log(`✅ Updated email to ${emailMappings[placeholder]}`);
                    }
                });
            }
        }
        
        // Update all nodes
        workflowData.nodes.forEach(updateNodeParameters);
        
        // Write the updated workflow back to file
        fs.writeFileSync(workflowPath, JSON.stringify(workflowData, null, 2));
        
        console.log('✅ N8N workflow configuration updated successfully!');
        console.log('📁 Updated file: legal-ai-system-n8n-workflow.json');
        
    } catch (error) {
        console.error('❌ Failed to update N8N workflow:', error.message);
        process.exit(1);
    }
}

// Run the update
updateN8NWorkflow();
EOF

    print_success "Created N8N configuration update script"
}

# Create test script
create_test_script() {
    print_status "Creating test script..."
    
    cat > test-workflow.js << 'EOF'
/**
 * Test Script for Legal AI System
 * Tests the basic functionality of the setup
 */

const { LegalAISetup } = require('./setup-google-sheets');
const { GoogleDriveSetup } = require('./setup-google-drive');

async function testSetup() {
    try {
        console.log('🧪 Testing Legal AI System Setup...');
        
        // Test Google Sheets setup
        console.log('\n📊 Testing Google Sheets setup...');
        const sheetsSetup = new LegalAISetup();
        // Note: This would actually create sheets, so we'll just test the class instantiation
        console.log('✅ Google Sheets setup class loaded successfully');
        
        // Test Google Drive setup
        console.log('\n📁 Testing Google Drive setup...');
        const driveSetup = new GoogleDriveSetup();
        console.log('✅ Google Drive setup class loaded successfully');
        
        // Test environment variables
        console.log('\n🔧 Testing environment variables...');
        require('dotenv').config();
        
        const requiredEnvVars = [
            'GOOGLE_PROJECT_ID',
            'GOOGLE_CLIENT_EMAIL',
            'OPENAI_API_KEY',
            'LEGAL_TEAM_EMAIL'
        ];
        
        let missingVars = [];
        requiredEnvVars.forEach(varName => {
            if (!process.env[varName]) {
                missingVars.push(varName);
            }
        });
        
        if (missingVars.length > 0) {
            console.log('⚠️  Missing environment variables:', missingVars.join(', '));
            console.log('Please update your .env file with the missing values');
        } else {
            console.log('✅ All required environment variables are set');
        }
        
        console.log('\n🎉 Test completed successfully!');
        console.log('\n📋 Next steps:');
        console.log('1. Update your .env file with actual values');
        console.log('2. Run: npm run setup-all');
        console.log('3. Run: node update-n8n-config.js');
        console.log('4. Import the workflow into N8N');
        
    } catch (error) {
        console.error('❌ Test failed:', error.message);
        process.exit(1);
    }
}

testSetup();
EOF

    print_success "Created test script"
}

# Create README file
create_readme() {
    print_status "Creating README documentation..."
    
    cat > README.md << 'EOF'
# Legal AI System for N8N

A comprehensive legal AI system that automates document processing, contract analysis, and legal memo generation using N8N workflows.

## Features

- **Document Summary Workflow**: Automatically processes incoming legal documents via Gmail
- **Contract Analysis Workflow**: Analyzes contracts uploaded to Google Drive
- **Main AI Agent**: Central hub that can access all information and draft legal memos
- **Google Sheets Integration**: Stores all processed data in organized spreadsheets
- **Email Automation**: Sends summaries and memos to legal teams

## System Architecture

```
┌─────────────────┐    ┌──────────────────┐    ┌─────────────────┐
│   Gmail Trigger │    │  Google Drive    │    │   Chat Trigger  │
│  (Documents)    │    │   Trigger        │    │  (Main Agent)   │
│                 │    │  (Contracts)     │    │                 │
└─────────┬───────┘    └─────────┬────────┘    └─────────┬───────┘
          │                      │                       │
          ▼                      ▼                       ▼
┌─────────────────┐    ┌──────────────────┐    ┌─────────────────┐
│ Document        │    │ Contract         │    │ Main AI Agent   │
│ Analysis        │    │ Analysis         │    │ (Legal Assistant)│
│ Workflow        │    │ Workflow         │    │                 │
└─────────┬───────┘    └─────────┬────────┘    └─────────┬───────┘
          │                      │                       │
          ▼                      ▼                       ▼
┌─────────────────┐    ┌──────────────────┐    ┌─────────────────┐
│ Google Sheets   │    │ Google Sheets    │    │ Gmail Sender    │
│ (Summaries)     │    │ (Contracts)      │    │ (Memos)         │
└─────────────────┘    └──────────────────┘    └─────────────────┘
```

## Prerequisites

- Node.js (v16 or higher)
- npm
- Google Cloud Platform account
- OpenAI API key
- Gmail account
- N8N instance

## Installation

1. **Clone or download the files**
   ```bash
   # All files should be in your project directory
   ```

2. **Run the setup script**
   ```bash
   chmod +x setup-environment.sh
   ./setup-environment.sh
   ```

3. **Configure environment variables**
   ```bash
   cp .env.example .env
   # Edit .env with your actual values
   ```

4. **Set up Google services**
   ```bash
   npm run setup-all
   ```

5. **Update N8N workflow configuration**
   ```bash
   node update-n8n-config.js
   ```

6. **Import workflow into N8N**
   - Copy the contents of `legal-ai-system-n8n-workflow.json`
   - Import into your N8N instance

## Configuration

### Google Cloud Setup

1. Create a Google Cloud Project
2. Enable the following APIs:
   - Google Sheets API
   - Google Drive API
   - Gmail API
3. Create a Service Account
4. Download the service account JSON key
5. Update the `.env` file with your credentials

### OpenAI Setup

1. Create an OpenAI account
2. Generate an API key
3. Add the key to your `.env` file

### Gmail Setup

1. Set up OAuth2 credentials for Gmail
2. Configure the refresh token
3. Update the `.env` file

## Usage

### Document Processing

1. Send legal documents to your configured Gmail account
2. The system automatically:
   - Downloads and saves documents to Google Drive
   - Extracts text and analyzes content
   - Saves summaries to Google Sheets
   - Sends email notifications to your legal team

### Contract Analysis

1. Upload contracts to the designated Google Drive folder
2. The system automatically:
   - Downloads and analyzes contracts
   - Identifies key clauses and risks
   - Saves analysis to Google Sheets
   - Sends detailed reports via email

### AI Legal Assistant

1. Use the chat interface in N8N
2. Ask questions like:
   - "What deadlines are due soon?"
   - "What are the key issues in the Acme vs Zephyr case?"
   - "Draft an internal memo for the contract review"
   - "What indemnity clauses exist in our contracts?"

## File Structure

```
legal-ai-system/
├── legal-ai-system-n8n-workflow.json    # Main N8N workflow
├── setup-google-sheets.js               # Google Sheets setup script
├── setup-google-drive.js                # Google Drive setup script
├── setup-environment.sh                 # Environment setup script
├── update-n8n-config.js                 # N8N configuration updater
├── test-workflow.js                     # Test script
├── package.json                         # Node.js dependencies
├── .env.example                         # Environment template
└── README.md                           # This file
```

## Troubleshooting

### Common Issues

1. **Authentication Errors**
   - Verify your Google service account credentials
   - Check API permissions
   - Ensure OAuth2 tokens are valid

2. **Sheet/Folder Access Issues**
   - Verify folder IDs in the workflow
   - Check sharing permissions
   - Ensure service account has access

3. **N8N Import Issues**
   - Verify the workflow JSON is valid
   - Check that all node types are supported
   - Update N8N to the latest version

### Support

For issues and questions:
1. Check the N8N documentation
2. Verify your Google Cloud setup
3. Test individual components using the test script

## License

MIT License - Feel free to modify and use for your legal practice.

## Contributing

Contributions are welcome! Please feel free to submit issues and enhancement requests.
EOF

    print_success "Created README documentation"
}

# Main setup function
main() {
    print_status "Starting Legal AI System environment setup..."
    
    check_nodejs
    check_npm
    install_dependencies
    create_env_file
    create_n8n_config_script
    create_test_script
    create_readme
    
    print_success "Environment setup completed successfully!"
    print_warning "Next steps:"
    echo "1. Edit .env file with your actual configuration values"
    echo "2. Run: npm run setup-all"
    echo "3. Run: node update-n8n-config.js"
    echo "4. Import the workflow into N8N"
    echo ""
    print_status "For detailed instructions, see README.md"
}

# Run the setup
main "$@"